
package com.scalablemind.jaxws.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderServiceImpl", targetNamespace = "http://impl.jaxws.scalablemind.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateOrder", targetNamespace = "http://impl.jaxws.scalablemind.com/", className = "com.scalablemind.jaxws.impl.UpdateOrder")
    @ResponseWrapper(localName = "updateOrderResponse", targetNamespace = "http://impl.jaxws.scalablemind.com/", className = "com.scalablemind.jaxws.impl.UpdateOrderResponse")
    @Action(input = "http://impl.jaxws.scalablemind.com/OrderServiceImpl/updateOrderRequest", output = "http://impl.jaxws.scalablemind.com/OrderServiceImpl/updateOrderResponse")
    public String updateOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
